export const devices = [
  {
    id: "1",
    name: "Prophet 5",
    type: "Analog Polysynth",
    port: "MIDI 1",
    isConnected: true,
    hasPatches: true,
    patchCount: 200,
    isManuallyAdded: false,
    midiActivity: {
      in: false,
      out: false,
    },
  },
  {
    id: "3",
    name: "Analog Rytm MKII",
    type: "Drum Machine",
    port: "MIDI 2",
    isConnected: true,
    hasPatches: true,
    patchCount: 128,
    isManuallyAdded: false,
    midiActivity: {
      in: false,
      out: false,
    },
  },
  {
    id: "4",
    name: "Analog Four MKII",
    type: "Analog Synth",
    port: "MIDI 3",
    isConnected: true,
    hasPatches: true,
    patchCount: 128,
    isManuallyAdded: false,
    midiActivity: {
      in: false,
      out: false,
    },
  },
  {
    id: "5",
    name: "Analog Heat +FX",
    type: "Analog Effects",
    port: "MIDI 4",
    isConnected: false,
    hasPatches: false,
    isManuallyAdded: false,
    midiActivity: {
      in: false,
      out: false,
    },
  },
  {
    id: "2",
    name: "Minimoog Model D",
    type: "Analog Monosynth",
    port: "USB MIDI 1",
    isConnected: true,
    hasPatches: false,
    isManuallyAdded: true,
    midiActivity: {
      in: false,
      out: false,
    },
  },
]
